Create new readme, update compile script

diff --git a/create-chess b/create-chess
--- a/create-chess
+++ b/create-chess
@@ -7,7 +7,13 @@ javac -d bin $(find src -name *.java)
 
 
 if [ $? ]; then
-  echo "Done!"
+  echo "Successfully compiled. Creating JAR executable."
+  jar cmvf META-INF/MANIFEST.MF Chess.jar bin
+  if [ $? ]; then
+    echo "Done"
+  else
+    echo "Error while creating JAR file, try again."
+  fi
 else
-  echo "!!Error during compiling!!"
+  echo "Error during compiling! Try re-downloading and try again."
 fi
